#!/usr/bin/env bash
#n to get subdomain information
get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    result=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:')
    
    if [[ -n "$result" ]]; then
        record_type=$(echo "$result" | awk 'NR==2 {print $4}')
        destination=$(echo "$result" | awk 'NR==2 {print $5}')
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
        echo "No information found for the subdomain $subdomain"
    fi
}

# Main script
domain=$1
subdomain=$2

if [[ -z "$domain" ]]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

if [[ -n "$subdomain" ]]; then
    get_subdomain_info "$domain" "$subdomain"
else
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
fi

