#!/usr/bin/env bash
#Bash script that will display information about subdomains.
get_subdomain_info() {
    local domain=$1
    local subdomain=$2

    result=$(dig +short "$subdomain.$domain")
    
    if [[ -n "$result" ]]; then
        echo "The subdomain $subdomain is an A record and points to $result"
    else
        echo "No information found for the subdomain $subdomain"
    fi
}

# Main script
domain=$1
subdomain=$2

if [[ -z "$domain" ]]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

if [[ -n "$subdomain" ]]; then
    get_subdomain_info "$domain" "$subdomain"
else
    for sub in www lb-01 web-01 web-02; do
        get_subdomain_info "$domain" "$sub"
    done
fi
