#!/usr/bin/env bash
#package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the directory if it doesn't exist
sudo mkdir -p /var/www/html

# Create the HTML file with "Hello World!" content
sudo echo "Hello World!" | sudo tee /var/www/html/index.html


# Ensure Nginx is configured to listen on port 80 and serve the HTML file
sudo bash -c cat << 'EOF' > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
}
EOF

# Reload Nginx configuration
sudo ervice nginx restart
