#!/usr/bin/env bash
#pacckage list and install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a simple HTML page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Ensure Nginx is configured to listen on port 80 and serve the HTML file, and add redirection
sudo bash -c 'cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Restart nginx using the service command
sudo service nginx restart
