#!/usr/bin/env bash
# Update the package list and install HAProxy
sudo apt-get update
apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6
sudo apt-get install -y haproxy=2.6.\*


# Backup the original HAProxy configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 100.26.232.23:80 check
    server web02 34.232.78.109:80 check
EOF

# Enable and start the HAProxy service
sudo systemctl enable haproxy
sudo systemctl start haproxy

# Output status of HAProxy to ensure it's running
sudo systemctl status haproxy
