#!/usr/bin/env bash
# List TCP listening sockets and UDP listening sockets
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

lsof -i -n -P | grep LISTEN | grep -E "(TCP|IPv4)" | awk '{print "tcp        0      0 "$9"                     *:*                     LISTEN      "$2"/"$1}'

lsof -i -n -P | grep UDP | grep LISTEN | awk '{print "udp        0      0 "$9"                     *:*                                  "$2"/"$1}'

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# List UNIX domain sockets
lsof -U -n -P | grep LISTEN | awk '{print "unix "$5" "$6" "$7" "$8" "$9" "$10" "$2"/"$1}'
