#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely
# Respond to SIGTERM with "I am invincible!!!"
trap 'echo "I am invincible!!!"' SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
