#!/usr/bin/env bash
# Display the content of the current directory in a list format
# Only display the part of the name after the first dash
for file in *; do
    if [ -f "$file" ]; then
        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_after_dash"
    fi
done
