#!/usr/bin/env bash

# Backup the current /etc/hosts file
cp /etc/hosts /etc/hosts.bak

# Copy /etc/hosts to a new file in the home directory
cp /etc/hosts ~/hosts.new

# Function to add or replace an entry in /etc/hosts
add_or_replace_entry() {
    local ip="$1"
    local hostname="$2"
    local file="$HOME/hosts.new"
    
    # Remove any existing lines containing the hostname
    sed -i "/[[:space:]]${hostname}$/d" "$file"
    
    # Add the new entry
    echo "${ip} ${hostname}" >> "$file"
}

# Add or replace entries
add_or_replace_entry "127.0.0.2" "localhost"
add_or_replace_entry "8.8.8.8" "facebook.com"

# Copy the modified hosts file back to /etc/hosts
cp -f ~/hosts.new /etc/hosts
