#!/usr/bin/env bash
#Bash script that creates an RSA key pair.

# Define variables
KEY_NAME="school"
KEY_BITS=4096
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE
